dist: focal
language: python
python:
  - "3.11"

before_install:
  - pip install --upgrade pip
  - pip install "setuptools<59" "wheel" 
  - pip install "awsebcli==3.20.10" 
install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  - black --check . || true
  - flake8 --max-line-length=150 swe1Project/ 
  - coverage run manage.py test 
  - env

after_scripts:
  - coveralls


before_deploy:
  - rm -rf .git  # Remove unnecessary Git files
  - export VERSION_LABEL="travis-$(date +%Y%m%d%H%M%S)"  # Generate unique version
  - zip -r deploy.zip * -x "venv/*" "*.git*" "*.pyc" "__pycache__/*" ".travis.yml" "db.sqlite3"
  - ls -lh deploy.zip  # Check ZIP size
  - unzip -l deploy.zip  # Verify contents
  - aws s3 cp deploy.zip s3://elasticbeanstalk-us-east-2-639584540069/
  - aws elasticbeanstalk create-application-version --application-name swe1Project --version-label "$VERSION_LABEL" --source-bundle S3Bucket=elasticbeanstalk-us-east-2-639584540069,S3Key=deploy.zip
  - aws elasticbeanstalk update-environment --environment-name dishaenv --version-label "$VERSION_LABEL"





deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: travis-env
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: Dishagaonkar/travis
    branch: main
  skip_cleanup: 'true'
  version_label: "$VERSION_LABEL"


