dist: focal
language: python
python:
  - "3.10"
  - "3.11"

before_install:
  - pip install --upgrade pip
  - pip install "setuptools<59" "wheel" 
  - pip install "awsebcli==3.20.10" 
install:
  - pip install -r requirements.txt


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: travis-env
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: Dishagaonkar/travis
    branch: main
  skip_cleanup: 'true'

