dist: focal
language: python
python:
  - "3.11"

before_install:
  - pip install --upgrade pip
  - pip install "setuptools<59" "wheel" 
  - pip install "awsebcli==3.20.10" 
install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  - black --check . 
  - flake8 --max-line-length=150 swe1Project/ 
  - coverage run manage.py test 
  - env

after_scripts:
  - coveralls


before_deploy:
  - zip -r deploy.zip .  # Package the full project
  - ls -lh deploy.zip  # Check ZIP file size
  - unzip -l deploy.zip  # List contents of ZIP for debugging
  - pip install awscli
  - aws configure set aws_access_key_id "$AWS_ID"
  - aws configure set aws_secret_access_key "$AWS_KEY"
  - aws configure set default.region "us-east-2"
  - aws configure list
  - aws s3 ls s3://elasticbeanstalk-us-east-2-639584540069/




deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: travis-env
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: Dishagaonkar/travis
    branch: main
  skip_cleanup: 'true'


